#!/usr/bin/env python3
"""Build a root-level Markdown inventory for production/shadow cleanup."""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = PROJECT_ROOT / "handoff" / "root_markdown_inventory_20260729.md"
ACTIVE_MANIFEST = PROJECT_ROOT / "report" / "group_a_plus" / "latest" / "strategy.json"

PRODUCTION_SOURCE_NAMES = {
    "README.md",
    "GROUP_A_GOLDEN1_0531_RELEASE.md",
    "DATA_REFRESH_AUTOMATION.md",
    "FUBON_SDK_SETUP.md",
}

CURRENT_SESSION_RECORD_NAMES = {
    "FINRL_CONSOLIDATION_ARCHIVE_CANDIDATES_20260729.md",
}

REVIEW_REPORT_MARKERS = (
    "AUDIT",
    "CHECK",
    "CHECKLIST",
    "EVALUATION",
    "MEMO",
    "REPORT",
    "REVIEW",
    "SUMMARY",
    "VALIDATION",
)

GOVERNANCE_MARKERS = (
    "CHAIN_FIX",
    "CONTRACT",
    "GOVERNANCE",
    "OPS_HEALTH",
    "POINT_IN_TIME_STORE",
    "RETENTION",
    "STALE_INPUT_FIX",
)

IMPROVEMENT_RESEARCH_MARKERS = (
    "BACKTEST",
    "BRANCH",
    "CALIBRATION",
    "CASH",
    "CONFORMAL",
    "GATE",
    "IMPROVEMENT",
    "IMPROVEMENTS",
    "NEXT_STEP",
    "OVERLAY",
    "PRELIMINARY",
    "PROXY",
    "RANKING",
)


def _walk_strings(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value]
    if isinstance(value, dict):
        out: list[str] = []
        for item in value.values():
            out.extend(_walk_strings(item))
        return out
    if isinstance(value, list):
        out: list[str] = []
        for item in value:
            out.extend(_walk_strings(item))
        return out
    return []


def _active_manifest_references() -> set[str]:
    if not ACTIVE_MANIFEST.exists():
        return set()
    payload = json.loads(ACTIVE_MANIFEST.read_text(encoding="utf-8"))
    refs: set[str] = set()
    for value in _walk_strings(payload):
        text = value.strip().replace("\\", "/")
        if text.endswith(".md"):
            refs.add(Path(text).name)
    return refs


def classify(name: str, active_refs: set[str]) -> tuple[str, str]:
    upper = name.upper()
    if name in PRODUCTION_SOURCE_NAMES:
        return "production_source", "explicit production/source-of-truth allowlist"
    if name in CURRENT_SESSION_RECORD_NAMES:
        return "current_session_record", "current consolidation/handoff working record"
    if name in active_refs:
        return "active_manifest_reference", "referenced by report/group_a_plus/latest/strategy.json"
    if "IMPORT_REVIEW" in upper or "CHANGELOG" in upper or "SHADOW_IMPORT" in upper:
        return "research_import_review", "external import/review/changelog"
    if "IMPORT" in upper and "FINRL_META" in upper:
        return "research_import_review", "FinRL meta import/governance review"
    if "HANDOFF" in upper or "HANDOVER" in upper or "WORK_LOG" in upper:
        return "handoff", "handoff/session continuation note"
    if "EXPERIMENT" in upper or "SWEEP" in upper or "OPTIMIZATION" in upper:
        return "experiment", "experiment/sweep/optimization record"
    if "RESEARCH" in upper or "SHADOW" in upper:
        return "research_shadow", "research or shadow-only record"
    if any(marker in upper for marker in GOVERNANCE_MARKERS):
        return "governance_record", "pipeline/ops/governance record"
    if any(marker in upper for marker in REVIEW_REPORT_MARKERS):
        return "review_report", "review/report/audit/check record"
    if any(marker in upper for marker in IMPROVEMENT_RESEARCH_MARKERS):
        return "improvement_research", "improvement/backtest/research note"
    if "RELEASE" in upper or "DEFINITION" in upper or "POLICY" in upper:
        return "possible_source_of_truth", "review before moving"
    return "unclassified_review_required", "manual review required"


def build_inventory(root: Path = PROJECT_ROOT) -> str:
    active_refs = _active_manifest_references()
    files = sorted(path.name for path in root.glob("*.md"))
    rows = []
    counts: Counter[str] = Counter()
    grouped: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for name in files:
        category, reason = classify(name, active_refs)
        counts[category] += 1
        grouped[category].append((name, reason))
        rows.append((name, category, reason))

    lines = [
        "# Root Markdown Inventory - 2026-07-29",
        "",
        "Generated by `scripts/report/build_root_markdown_inventory.py`.",
        "",
        "Purpose: classify root-level Markdown files before moving handoff, research, and experiment debt.",
        "",
        "Important: this is an inventory, not proof that a file is safe to move. Move files in small batches and re-run boundary tests.",
        "",
        "## Summary",
        "",
        "| Category | Count |",
        "| --- | ---: |",
    ]
    for category, count in sorted(counts.items()):
        lines.append(f"| `{category}` | {count} |")

    lines.extend(["", "## Active Manifest Markdown References", ""])
    if active_refs:
        for item in sorted(active_refs):
            lines.append(f"- `{item}`")
    else:
        lines.append("- none detected")

    lines.extend(["", "## Recommended Move Order", ""])
    lines.extend([
        "1. Move `research_import_review` files that are not active manifest references.",
        "2. Move older `handoff` files into dated `handoff/YYYY-MM/` batches.",
        "3. Move `experiment`, `research_shadow`, `improvement_research`, and `review_report` files after checking references.",
        "4. Keep `production_source`, `active_manifest_reference`, `current_session_record`, `governance_record`, and `possible_source_of_truth` in place until a dedicated migration updates all references.",
    ])

    lines.extend(["", "## Full Inventory", ""])
    for category in sorted(grouped):
        lines.extend(["", f"### {category}", ""])
        for name, reason in grouped[category]:
            lines.append(f"- `{name}` - {reason}")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    output = Path(args.output)
    if not output.is_absolute():
        output = PROJECT_ROOT / output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_inventory(), encoding="utf-8")
    print(f"Root Markdown inventory: {output}")


if __name__ == "__main__":
    main()
